name: aveoauth
description: A package for simplifying authentication in Flutter

environment:
  sdk: ">=2.17.6 <3.0.5"
  # flutter: ">=1.17.0"

dependencies:
  crypto: ^3.0.2
  firebase_auth: ^3.11.0
  firebase_core: ^1.24.0
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^5.0.0+2
  get_storage: ^2.0.3
  github_sign_in: ^0.0.5-dev.4
  google_sign_in: ^5.4.2
  local_auth: ^2.1.2
  sign_in_with_apple: ^4.1.0
  twitter_login: ^4.2.3
  path: ^1.8.1
  process_run: ^0.12.3+2
  recase: ^4.1.0
  http: ^0.13.5
  dcli: ^1.34.0
  pubspec: ^2.3.0
  version: ^3.0.2
  dart_style: ^2.2.4
  logger: ^1.1.0
  sms_autofill: ^2.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

executables:
  aveoauth: aveoauth
