// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8SePHWdLTtmDPMCq_sxZEFFD33m1dLgM',
    appId: '1:313488232645:web:136601aade1e73d033e0ac',
    messagingSenderId: '313488232645',
    projectId: 'authmelosmodule',
    authDomain: 'authmelosmodule.firebaseapp.com',
    storageBucket: 'authmelosmodule.appspot.com',
    measurementId: 'G-KZSZKVJ6FW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0UdQkoM28ve71rLvxapu2kDdxpUvKtTo',
    appId: '1:313488232645:android:7f2b75ec47110bb933e0ac',
    messagingSenderId: '313488232645',
    projectId: 'authmelosmodule',
    storageBucket: 'authmelosmodule.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaM8k4b3nBdMX7xTvYkXUxqL4VT8qGNF8',
    appId: '1:313488232645:ios:0974ead85ca40e9933e0ac',
    messagingSenderId: '313488232645',
    projectId: 'authmelosmodule',
    storageBucket: 'authmelosmodule.appspot.com',
    iosClientId: '313488232645-ikfsq0bbmun5qjigudasj329fb3805ce.apps.googleusercontent.com',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaM8k4b3nBdMX7xTvYkXUxqL4VT8qGNF8',
    appId: '1:313488232645:ios:0974ead85ca40e9933e0ac',
    messagingSenderId: '313488232645',
    projectId: 'authmelosmodule',
    storageBucket: 'authmelosmodule.appspot.com',
    iosClientId: '313488232645-ikfsq0bbmun5qjigudasj329fb3805ce.apps.googleusercontent.com',
    iosBundleId: 'com.example.example',
  );
}
