// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaXPtEitCoY2BC3hzwqJ-F856OENOEd78',
    appId: '1:426704782047:web:3aa61369929fcd5cbfdf6a',
    messagingSenderId: '426704782047',
    projectId: 'auth4-e6e7d',
    authDomain: 'auth4-e6e7d.firebaseapp.com',
    storageBucket: 'auth4-e6e7d.appspot.com',
    measurementId: 'G-NE3W04C9ZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKIYP4Hm1rBV4XaYFbvFG0TDLQTo4Jl_s',
    appId: '1:426704782047:android:26286f08928a9562bfdf6a',
    messagingSenderId: '426704782047',
    projectId: 'auth4-e6e7d',
    storageBucket: 'auth4-e6e7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkp1V8ej3nErb4dWUE2F98cHIvXTx7SDc',
    appId: '1:426704782047:ios:0e718ebef99f4f9ebfdf6a',
    messagingSenderId: '426704782047',
    projectId: 'auth4-e6e7d',
    storageBucket: 'auth4-e6e7d.appspot.com',
    iosClientId: '426704782047-prb8rdotmfblgm9t83fao7rni981alsj.apps.googleusercontent.com',
    iosBundleId: 'com.aveosoftware.applelogintest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkp1V8ej3nErb4dWUE2F98cHIvXTx7SDc',
    appId: '1:426704782047:ios:0e718ebef99f4f9ebfdf6a',
    messagingSenderId: '426704782047',
    projectId: 'auth4-e6e7d',
    storageBucket: 'auth4-e6e7d.appspot.com',
    iosClientId: '426704782047-prb8rdotmfblgm9t83fao7rni981alsj.apps.googleusercontent.com',
    iosBundleId: 'com.aveosoftware.applelogintest',
  );
}
